#! /bin/bash

IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' grafana-influxdb_con )

if [ xIP = x ] ; then
	echo " container grafana-influxdb_con is not running, please start container and do that again"
	exit 1
fi

docker run -v $(pwd)/src:/src -v $(pwd)/dst:/dst --env SRC_PATH=/src --env DST_PATH=/dst --env TASK=PUSH --env IP=$IP --name atop-pusher  atop-convert && \
docker rm atop-pusher

